version: '1'
networks:
  ps_network:
    driver: bridge

services:
  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    working_dir: /application
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      TZ: "${TIMEZONE}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - bdd_volume:/var/lib/mysql
    networks:
      ps_network:
        aliases:
          - bdd
  api:
    build: 
      context: './api'
    depends_on: 
      - mysql
    image: ps-api
    container_name: api
    restart: always
    ports:
      - "${API_PORT}:8000"
    volumes:
      - api_volume:/application
    networks:
      ps_network:
        aliases:
          - api

volumes:
  api_volume:
  bdd_volume:
